name: run-test-backend

on:
  workflow_dispatch:

jobs:
  compile-test-using-package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: "Run test backend on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: conda-ci
        auto-update-conda: true
        miniforge-version: latest

    - name: Install panda3d
      shell: bash -l {0}
      run: |
        conda install "panda3d=*=withegl*_4" -c olivier.roussel

    - name: Show conda config
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort

    - name: Debug info
      shell: bash -l {0}
      continue-on-error: true
      run: |
        ldd $CONDA_PREFIX/lib/libpandagl.so
        echo "-----------"
        ldd $CONDA_PREFIX/lib/libp3headlessgl.so
        echo "-----------"

    - name: Run backend test (offscreen)
      continue-on-error: true
      shell: bash -l {0}
      run: |
        sudo /usr/bin/Xvfb :0 -screen 0 1280x1024x24 &
        export DISPLAY=:0
        python test_backend_offscreen.py
        file test.jpg
