name: test-llvmpipe-install

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installer les dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils

      - name: Vérifier le rendu OpenGL
        run: |
          glxinfo | grep "OpenGL"